import os
import subprocess
import asyncio
import requests
import edge_tts
import whisper
from playwright.async_api import async_playwright

def generate_script():
    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        raise ValueError("OPENROUTER_API_KEY secret is not set in GitHub Secrets.")

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    prompt = (
        "Write a punchy, viral 15-second script for an Instagram Reel promoting an AI tool. "
        "Return ONLY the plain spoken voiceover script text with no stage directions, quotes, or formatting."
    )

    models_to_try = [
        "openrouter/auto",
        "anthropic/claude-sonnet-5",
        "anthropic/claude-3.5-sonnet"
    ]

    for model_slug in models_to_try:
        print(f"Attempting script generation with model: {model_slug}...")
        payload = {
            "model": model_slug,
            "messages": [{"role": "user", "content": prompt}]
        }

        try:
            res = requests.post(url, headers=headers, json=payload, timeout=30)
            data = res.json()

            if "choices" in data and len(data["choices"]) > 0:
                script_text = data["choices"][0]["message"]["content"].strip()
                print(f"Successfully generated script using {model_slug}!")
                return script_text
            else:
                print(f"Model {model_slug} returned non-standard response: {data}")
        except Exception as e:
            print(f"Request failed for model {model_slug}: {e}")

    raise KeyError("All OpenRouter model endpoints failed. Check API key or credits.")

async def generate_voiceover(text, output_path):
    voices = ["en-US-ChristopherNeural", "en-US-GuyNeural", "en-US-AriaNeural"]
    for voice in voices:
        print(f"Trying edge-tts voice: {voice}...")
        try:
            communicate = edge_tts.Communicate(text, voice)
            await communicate.save(output_path)
            print(f"Voiceover successfully rendered with {voice}!")
            return
        except Exception as e:
            print(f"Voice {voice} failed: {e}. Retrying with next voice...")
            await asyncio.sleep(2)
            
    raise RuntimeError("All edge-tts voice endpoints failed.")

def format_timestamp(seconds):
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int((seconds - int(seconds)) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"

def generate_subtitles(audio_path, srt_path):
    print("[Whisper] Loading model and generating captions...")
    model = whisper.load_model("tiny")
    result = model.transcribe(audio_path)
    
    with open(srt_path, "w", encoding="utf-8") as f:
        for i, segment in enumerate(result["segments"], start=1):
            start = format_timestamp(segment["start"])
            end = format_timestamp(segment["end"])
            text = segment["text"].strip()
            f.write(f"{i}\n{start} --> {end}\n{text}\n\n")
            
    print(f"[Whisper] Subtitles generated at {srt_path}")

async def record_screen(target_url, output_dir):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            viewport={"width": 1080, "height": 1920},
            record_video_dir=output_dir,
            record_video_size={"width": 1080, "height": 1920}
        )
        page = await context.new_page()
        print(f"Navigating to {target_url}...")
        await page.goto(target_url, wait_until="networkidle")
        await page.wait_for_timeout(15000)  # Record 15 seconds
        await context.close()
        await browser.close()

def assemble_final_reel(raw_video_path, audio_path, srt_path, output_path):
    print("[FFmpeg] Merging video, audio, and burning subtitles...")
    
    # FFmpeg command to combine raw screen capture, voiceover audio, and burned subtitles centered on screen
    command = [
        "ffmpeg", "-y",
        "-i", raw_video_path,
        "-i", audio_path,
        "-vf", f"subtitles={srt_path}:force_style='FontSize=20,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,BorderStyle=1,Outline=2,Alignment=2'",
        "-c:v", "libx264",
        "-c:a", "aac",
        "-shortest",
        output_path
    ]
    
    subprocess.run(command, check=True)
    print(f"[FFmpeg] Final Reel compiled successfully: {output_path}")

async def main():
    os.makedirs("output", exist_ok=True)
    tool_url = os.getenv("TOOL_URL", "https://aicarousels.com")

    print("[1/5] Recording target website screen...")
    await record_screen(tool_url, "output")

    # Locate raw webm/mp4 generated by Playwright
    raw_files = [os.path.join("output", f) for f in os.listdir("output") if f.endswith('.webm') or f.endswith('.mp4')]
    if not raw_files:
        raise FileNotFoundError("Playwright failed to produce a screen recording file.")
    raw_video = raw_files[0]

    print("[2/5] Generating script via AI...")
    script_text = generate_script()
    print(f"Generated Script:\n\"{script_text}\"")

    print("[3/5] Rendering voiceover via edge-tts...")
    audio_file = "output/voice.mp3"
    await generate_voiceover(script_text, audio_file)

    print("[4/5] Transcribing audio to SRT via OpenAI Whisper...")
    srt_file = "output/subtitles.srt"
    generate_subtitles(audio_file, srt_file)

    print("[5/5] Assembling final dynamic video...")
    final_video = "output/final_reel.mp4"
    assemble_final_reel(raw_video, audio_file, srt_file, final_video)

    print("Pipeline completed cleanly! Finished reel stored at output/final_reel.mp4")

if __name__ == "__main__":
    asyncio.run(main())
